name: Build and deploy on PR

on:
  pull_request:
    branches:
      - master

jobs:
  build:
    name: zola-deploy-action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@deployment-issue
      - name: Build and deploy
        uses: shalzz/zola-deploy-action@master
        env:
          PAGES_BRANCH: gh-pages
          BUILD_DIR: .
          TOKEN: ${{ secrets.TOKEN }}
